import pandas as pd
import yake

def removing_posts_by_mods (df: pd.DataFrame) -> pd.DataFrame:
    """
    This is used to remove posts made by the Auto
    Moderator bot
    """
    i = df[df['author'] == 'AutoModerator'].index
    return df.drop(i)

def cleaner (x: list) -> list:
    """
    When using yake, it returns a list of tuples,
    each tuple has a string and a number. Since
    there is no need for the number, this removes it

    param:
        x (list): list of tuples generated by yake
    returns:
        list: list of strings only
    """
    clean_list = []

    for i in x:
        if type(i) == tuple:
            clean_list.append(i[0])

    return clean_list

def extract_keywords (df: pd.DataFrame) -> pd.DataFrame:
    """
    Uses yake to extract keywords from the title
    and body (text) of a post.

    param:
        df (pd.DataFrame): DataFrame with title
                           and text as columns
    returns:
        pd.DataFrame: DataFrame with keywords
                      column added
    """
    df['text'] = df['text'].fillna('<NA>')

    lang = "en"
    max_ngram_size = 1
    deduplication_threshold = 0.9
    num_keywords = 10

    kw = yake.KeywordExtractor(
        lan=lang,
        n=max_ngram_size,
        dedupLim=deduplication_threshold,
        top=num_keywords,
        features=None)

    keywords_text = df['text'].apply(
        lambda x: cleaner(kw.extract_keywords(x)))

    keywords_title = df['title'].apply(
        lambda x: cleaner(kw.extract_keywords(x)))

    df['keywords'] = keywords_text + keywords_title
    df['keywords'] = df['keywords'].apply(lambda x: set(x))

    return df

def transform (input_path: str, output_path: str) -> None:
    """
    Processes the csv created by extract()
    Removes posts by moderators
    Converts 'created' column to pandas datetime
    Extracts keywords from 'title' and 'text' columns

    param:
        input_path (str): Path to the csv file,
                          same used by extract()
        output_path (str): Where the file will
                           be saved
    """
    df = pd.read_csv(input_path)

    df = removing_posts_by_mods(df)

    df['created'] = pd.to_datetime(df['created'], unit='s')

    df = extract_keywords(df)

    df.to_csv(output_path, index=False)

if __name__ == '__main__':
    input_file = '../output/extracted.csv'
    output_file = '../output/transformed.csv'

    transform(input_file, output_file)
    print('Finished transforming')